### ISSUE TITLE
自定义分享面板实现

### ISSUE THREAD

**Issue by 1107979819** [HADB/react-native-umeng-share#1]
Hello，由于很多应用场景是要自定义分享面板和平台，所以直接调用分享弹窗似乎满足不了这个需求。
是否可以开放单个平台分享的调用接口？

**Comment by HADB** [comment]
Hi, 这个项目目的是为了在react native上快速集成友盟分享，如果需要自定义分享面板和平台的话，需要自己做一些封装，欢迎fork。

**Comment by 1107979819** [comment]
好的，谢谢
