### ISSUE TITLE
Can not install the repository.

### ISSUE THREAD

**Issue by jiangsumadai** [HADB/react-native-umeng-share#2]
When i begin to install, the teminal shows '404 Registry returned 404 for GET on https://registry.npmjs.org/react-native-umeng-share'

404 'react-native-umeng-share' is not in the npm registry

**Comment by HADB** [comment]
Hi, this package didn't upload to npm. You can use the github link.
npm install --save react-native-umeng-share@https://github.com/HADB/react-native-umeng-share.git
